# Generated by Django 5.1.4 on 2025-01-06 21:41

import django.db.models.deletion
import finance_api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=finance_api.utils.get_current_date)),
                ('description', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance_api.incomesource')),
            ],
        ),
    ]
