# Generated by Django 5.1.4 on 2025-01-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0002_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
