# Generated by Django 5.1.4 on 2025-01-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0004_expensecategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expensecategory',
            table='expense_categories',
        ),
        migrations.AlterModelTable(
            name='income',
            table='incomes',
        ),
        migrations.AlterModelTable(
            name='incomesource',
            table='income_sources',
        ),
    ]
