# Generated by Django 5.1.4 on 2025-01-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0006_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'balances',
            },
        ),
    ]
