# Generated by Django 5.1.4 on 2025-01-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0007_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
