# Generated by Django 5.1.4 on 2025-01-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0008_expense_balance_after_income_balance_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
