# Generated by Django 5.1.4 on 2025-01-19 13:36

import django.db.models.deletion
import finance_api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0009_balance_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'saving_categories',
            },
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=finance_api.utils.get_current_date)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance_api.savingcategory')),
            ],
            options={
                'db_table': 'savings',
            },
        ),
    ]
