# Generated by Django 5.1.4 on 2025-01-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0010_savingcategory_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='total_savings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
