# Generated by Django 5.1.4 on 2025-01-19 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0011_balance_total_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance_api.expensecategory'),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance_api.incomesource'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance_api.savingcategory'),
        ),
    ]
