# Generated by Django 5.1.4 on 2025-03-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0012_alter_expense_category_alter_income_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingcategory',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
