services:
  backend:
    environment:
      - MODE=dev
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend,172.16.10.203
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "4200:4200"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
