services:
  backend:
    container_name: finance-manager-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/db
    environment:
      - MODE=prod
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
    command: ["/usr/local/bin/backend.sh"]

  # frontend:
  #   container_name: finance-manager-frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     args:
  #       NODE_ENV: production
  #   ports:
  #     - "4288:80"
  #   depends_on:
  #     - backend
  #   environment:
  #     - NODE_ENV=production

  frontend:
    container_name: finance-manager-backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "4200:4200"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

volumes:
  sqlite_data: